services:
  - type: web
    name: calendar-booking
    runtime: docker
    repo: https://github.com/DimaKabanov/ai-for-developers-project-386
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_LEVEL
        value: info
      - key: SECRET_KEY_BASE
        generateValue: true
    healthCheckPath: /up
    plan: free
    autoDeploy: true
